# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'Update deps: '
      include: 'scope'
    assignees:
      - 'uKaigo'
    open-pull-requests-limit: 10
